/**
 * 海报墙图片生成工具
 * 基于 uni-app canvas 绘制海报墙并导出为 JPEG
 */

function getImageInfo(src) {
  return new Promise((resolve, reject) => {
    uni.getImageInfo({
      src,
      success: (res) => resolve(res),
      fail: (err) => reject(err)
    })
  })
}

async function loadImagesWithLimit(imageUrls, limit = 5) {
  if (!imageUrls || imageUrls.length === 0) return []

  const results = new Array(imageUrls.length)
  let index = 0

  async function worker() {
    while (index < imageUrls.length) {
      const currentIndex = index++
      try {
        const res = await getImageInfo(imageUrls[currentIndex])
        results[currentIndex] = { success: true, path: res.path }
      } catch (e) {
        results[currentIndex] = { success: false, error: e }
      }
    }
  }

  const workers = []
  const workerCount = Math.min(limit, imageUrls.length)
  for (let i = 0; i < workerCount; i++) {
    workers.push(worker())
  }
  await Promise.all(workers)
  return results
}

/**
 * 生成海报墙分享图片
 * @param {Object} options
 * @param {string} options.title - 主标题
 * @param {string} options.subtitle - 副标题/统计
 * @param {Array} options.movies - 电影列表，每项需包含 { poster, title }
 * @param {string} options.canvasId - canvas 标识，默认 'shareCanvas'
 * @param {Object} options.componentThis - 页面/组件实例 this（某些平台需要）
 * @returns {Promise<string>} 生成的临时图片路径
 */
export function generatePosterWallImage({
  title,
  subtitle,
  movies,
  canvasId = 'shareCanvas',
  componentThis = null
}) {
  return new Promise(async (resolve, reject) => {
    try {
      const ctx = uni.createCanvasContext(canvasId, componentThis)

      // 画布布局参数
      const CANVAS_WIDTH = 750
      const COLS = 6
      const POSTER_W = 100
      const POSTER_H = 150
      const NAME_H = 18
      const CELL_H = POSTER_H + NAME_H
      const GAP_X = 10
      const GAP_Y = 15
      const MARGIN_X = (CANVAS_WIDTH - COLS * POSTER_W - (COLS - 1) * GAP_X) / 2
      const HEADER_H = 140
      const FOOTER_H = 60

      const rows = Math.ceil(movies.length / COLS)
      const canvasHeight = HEADER_H + rows * (CELL_H + GAP_Y) - GAP_Y + FOOTER_H

      // 1. 绘制背景
      ctx.setFillStyle('#f8f9fa')
      ctx.fillRect(0, 0, CANVAS_WIDTH, canvasHeight)

      // 2. 绘制标题
      ctx.setFillStyle('#1a1a1a')
      ctx.setFontSize(26)
      ctx.setTextAlign('center')
      ctx.fillText(title, CANVAS_WIDTH / 2, 60)

      // 3. 绘制副标题
      ctx.setFillStyle('#666666')
      ctx.setFontSize(16)
      ctx.fillText(subtitle, CANVAS_WIDTH / 2, 100)

      // 4. 预加载海报图片
      const posterUrls = movies.map((m) => m.poster || '').filter(Boolean)
      const loadedImages = await loadImagesWithLimit(posterUrls, 5)
      const imageMap = {}
      posterUrls.forEach((url, idx) => {
        imageMap[url] = loadedImages[idx]
      })

      // 5. 绘制海报和名字
      movies.forEach((movie, index) => {
        const col = index % COLS
        const row = Math.floor(index / COLS)
        const x = MARGIN_X + col * (POSTER_W + GAP_X)
        const y = HEADER_H + row * (CELL_H + GAP_Y)

        const imgInfo = imageMap[movie.poster]
        if (imgInfo && imgInfo.success) {
          ctx.drawImage(imgInfo.path, x, y, POSTER_W, POSTER_H)
        } else {
          // 占位色块
          ctx.setFillStyle('#e0e0e0')
          ctx.fillRect(x, y, POSTER_W, POSTER_H)
          if (movie.title) {
            ctx.setFillStyle('#999999')
            ctx.setFontSize(20)
            ctx.setTextAlign('center')
            ctx.fillText(movie.title[0], x + POSTER_W / 2, y + POSTER_H / 2 + 8)
          }
        }

        // 电影名字
        ctx.setFillStyle('#333333')
        ctx.setFontSize(12)
        ctx.setTextAlign('center')
        let displayTitle = movie.title || ''
        if (displayTitle.length > 7) {
          displayTitle = displayTitle.slice(0, 7) + '...'
        }
        ctx.fillText(displayTitle, x + POSTER_W / 2, y + POSTER_H + 14)
      })

      // 6. 绘制底部
      ctx.setFillStyle('#bbbbbb')
      ctx.setFontSize(12)
      ctx.setTextAlign('center')
      ctx.fillText('Generated by MovieDate', CANVAS_WIDTH / 2, canvasHeight - 20)

      // 7. 导出为 JPG
      ctx.draw(false, () => {
        setTimeout(() => {
          uni.canvasToTempFilePath({
            x: 0,
            y: 0,
            width: CANVAS_WIDTH,
            height: canvasHeight,
            canvasId,
            fileType: 'jpg',
            quality: 0.92,
            success: (res) => resolve(res.tempFilePath),
            fail: (err) => reject(err)
          }, componentThis)
        }, 300)
      })
    } catch (error) {
      reject(error)
    }
  })
}
